<?php

namespace AppBundle\Repository;

/**
 * ArmyStatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmyStatisticsRepository extends \Doctrine\ORM\EntityRepository
{
}
