<?php

namespace AppBundle\Repository;

/**
 * ArmyTrainTimersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmyTrainTimersRepository extends \Doctrine\ORM\EntityRepository
{
}
