<?php

namespace AppBundle\Repository;

/**
 * ArmyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmyRepository extends \Doctrine\ORM\EntityRepository
{
}
