<?php

namespace AppBundle\Repository;

/**
 * ArmyBattleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmyBattleRepository extends \Doctrine\ORM\EntityRepository
{
}
