<?php

namespace AppBundle\Repository;

/**
 * BattlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattlesRepository extends \Doctrine\ORM\EntityRepository
{
}
