<?php

namespace AppBundle\Repository;

/**
 * BattlesTempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattlesTempRepository extends \Doctrine\ORM\EntityRepository
{
}
