<?php

namespace AppBundle\Repository;

/**
 * BattleReportsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleReportsRepository extends \Doctrine\ORM\EntityRepository
{
}
