<?php

namespace AppBundle\Repository;

/**
 * BuildingUpdateTimersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingUpdateTimersRepository extends \Doctrine\ORM\EntityRepository
{
}
