<?php

namespace AppBundle\Repository;

/**
 * BuildingUpdatePropertiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingUpdatePropertiesRepository extends \Doctrine\ORM\EntityRepository
{
}
