<?php

namespace AppBundle\Repository;

/**
 * CastleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CastleRepository extends \Doctrine\ORM\EntityRepository
{
}
