<?php

namespace AppBundle\Repository;

/**
 * NewCastleCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewCastleCostRepository extends \Doctrine\ORM\EntityRepository
{
}
