<?php

namespace AppBundle\Repository;

/**
 * UserSpiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSpiesRepository extends \Doctrine\ORM\EntityRepository
{
}
