<?php

namespace AppBundle\Repository;

/**
 * UserUpdateResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserUpdateResourcesRepository extends \Doctrine\ORM\EntityRepository
{
}
