<?php

namespace AppBundle\Repository;

/**
 * UserMessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMessagesRepository extends \Doctrine\ORM\EntityRepository
{
}
